title: phamthainb
description: "Bờ lốc cá nhân, nơi để tôi chia sẻ mọi thứ..."
author:
  name: "phamthainb"
  email: "phamthai4643@gmail.com"
  url: "#"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-compose
  - jekyll-toc
#end plugins

# config toc
toc:
  max_level: 3 # default: 6

# Custom variables
owner: "phamthainb"
year: "2020"
google_analytics: G-XV52QZCWCD
